In [8]:
import pandas as pd

train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [2]:
train.head()

date  store  item  sales
0  2013-01-01      1     1     13
1  2013-01-02      1     1     11
2  2013-01-03      1     1     14
3  2013-01-04      1     1     13
4  2013-01-05      1     1     10

In [3]:
train.loc[train['item'] == 1].pivot(index='date', columns='store', values='sales').sum(0).values

array([36468, 51445, 45778, 41886, 30566, 30527, 27681, 49272, 42593,
       45168])

In [49]:
%%time
import numpy as np
import datetime

min_date, max_date = datetime.datetime(2013, 1, 1), datetime.datetime(2017, 12, 31)
days_len = 7
items = sorted(train['item'].drop_duplicates())

item_sales_dict = dict()
start_date = min_date
while True:
    end_date = start_date + datetime.timedelta(days=days_len)
    if end_date > max_date:
        break
    else:
        part = dict()
        start_str, end_str = start_date.strftime('%Y-%m-%d'), end_date.strftime('%Y-%m-%d')
        abs_parts = abs_data.loc[(abs_data['date'] >= start_str) * (abs_data['date'] < end_str)].sort_values(by=['date'])
        input_parts = train.loc[train['date'] >= start_str].loc[train['date'] < end_str].sort_values(by=['date'])
        output_parts = train.loc[train['date'] == end_str]
        for i, item in enumerate(items):
            input_pivot = input_parts.loc[input_parts['item'] == item].pivot(index='store', columns='date', values='sales')
            output_pivot = output_parts.loc[output_parts['item'] == item].pivot(index='store', columns='date', values='sales')
            part[item] = {
                'store_seq': list(filter(lambda x: f':item{item}-' in x, abs_parts['seq_cnv'])),
                'input': input_pivot.values,
                'output': output_pivot.values,
                'total': input_pivot.sum(0).values
            }
    item_sales_dict[start_str] = part
    print(start_str)
    start_date = start_date + datetime.timedelta(days=1)

2013-01-01
2013-01-02
2013-01-03
2013-01-04
2013-01-05
2013-01-06
2013-01-07
2013-01-08
2013-01-09
2013-01-10
2013-01-11
2013-01-12
2013-01-13
2013-01-14
2013-01-15
2013-01-16
2013-01-17
2013-01-18
2013-01-19
2013-01-20
2013-01-21
2013-01-22
2013-01-23
2013-01-24
2013-01-25
2013-01-26
2013-01-27
2013-01-28
2013-01-29
2013-01-30
2013-01-31
2013-02-01
2013-02-02
2013-02-03
2013-02-04
2013-02-05
2013-02-06
2013-02-07
2013-02-08
2013-02-09
2013-02-10
2013-02-11
2013-02-12
2013-02-13
2013-02-14
2013-02-15
2013-02-16
2013-02-17
2013-02-18
2013-02-19
2013-02-20
2013-02-21
2013-02-22
2013-02-23
2013-02-24
2013-02-25
2013-02-26
2013-02-27
2013-02-28
2013-03-01
2013-03-02
2013-03-03
2013-03-04
2013-03-05
2013-03-06
2013-03-07
2013-03-08
2013-03-09
2013-03-10
2013-03-11
2013-03-12
2013-03-13
2013-03-14
2013-03-15
2013-03-16
2013-03-17
2013-03-18
2013-03-19
2013-03-20
2013-03-21
2013-03-22
2013-03-23
2013-03-24
2013-03-25
2013-03-26
2013-03-27
2013-03-28
2013-03-29
2013-03-30
2013-03-31
2013-04-01

In [50]:
import json 
train_dict, test_dict = dict(), dict()
for k in item_sales_dict.keys():
    if k < '2016-01-01':
        train_dict[k] = item_sales_dict[k]
    else:
        test_dict[k] = item_sales_dict[k]
len(item_sales_dict), len(train_dict), len(test_dict)

(1819, 1095, 724)

In [56]:
val_dict = dict()
val_dates = np.random.choice(list(train_dict.keys()), round(len(train_dict) * 0.1), replace=False)
val_dates

array(['2014-01-09', '2014-12-14', '2014-08-25', '2014-02-06',
       '2015-05-19', '2015-01-06', '2013-05-17', '2013-08-31',
       '2014-11-29', '2013-05-19', '2014-03-09', '2015-05-14',
       '2013-08-21', '2015-11-13', '2014-12-03', '2014-11-14',
       '2014-12-28', '2015-09-10', '2013-09-12', '2014-06-10',
       '2015-07-06', '2013-02-10', '2015-04-08', '2013-10-06',
       '2015-09-16', '2015-03-17', '2014-12-25', '2014-10-07',
       '2014-01-31', '2014-12-24', '2014-03-31', '2015-08-16',
       '2013-03-18', '2013-01-29', '2014-07-02', '2013-09-02',
       '2014-04-13', '2015-01-24', '2013-09-04', '2013-09-25',
       '2013-05-22', '2014-12-26', '2015-01-02', '2015-02-20',
       '2013-05-14', '2014-11-06', '2014-01-21', '2014-02-12',
       '2015-02-16', '2014-03-13', '2014-09-20', '2014-03-15',
       '2015-06-05', '2014-06-19', '2015-10-10', '2015-01-14',
       '2014-09-06', '2013-02-07', '2015-06-24', '2013-09-15',
       '2014-08-29', '2015-02-22', '2013-10-11', '2014-

In [57]:
for d in val_dates:
    val_dict[d] = train_dict[d]
    del train_dict[d]
len(train_dict), len(val_dict)

(985, 110)

In [63]:
import pickle
pickle.dump(train_dict, open('sales_data/train_7days.pkl', 'wb'))
pickle.dump(val_dict, open('sales_data/val_7days.pkl', 'wb'))
pickle.dump(test_dict, open('sales_data/test_7days.pkl', 'wb'))

In [22]:
abs_data = pd.concat([
    pd.read_csv('train_bert_data/train_7days.csv'),
    pd.read_csv('train_bert_data/val_7days.csv'),
    pd.read_csv('train_bert_data/test_7days.csv')
])
abs_data.shape

(909500, 3)

In [ ]:
for store in train['store'].drop_duplicates():
    print(f'train store: {store}, items: {", ".join(train.loc[train["store"] == store, "item"].drop_duplicates().astype(str))}')
    print(f'test store: {store}, items: {", ".join(test.loc[test["store"] == store, "item"].drop_duplicates().astype(str))}')

In [ ]:
import numpy as np
min_sales, max_sales = 0, 300
range_ = 10
sales_blocks = dict()
base = ord('a')
for j, i in enumerate(np.arange(min_sales, max_sales, range_)):
    low, high = i, i + range_ - 1
    sales_blocks[(low, high)] = chr(base + j)
sales_blocks[(max_sales, 1000000)] = chr(base + len(sales_blocks))
sales_blocks

In [ ]:
def convert_code(sales_blocks, x):
    for k, v in sales_blocks.items():
        if x >= k[0] and x <= k[1]:
            return sales_blocks[k]

train['sales_processed'] = list(map(lambda x: convert_code(sales_blocks, x), train['sales']))
train.head()


In [ ]:
train.to_csv('data/train_converted.csv', index=False)

In [ ]:
%%time

import datetime

min_date, max_date = datetime.datetime(2013, 1, 1), datetime.datetime(2017, 12, 31)
days_len = 7
train['sales'] = train['sales'].astype(str)

for store in train['store'].drop_duplicates():
    start_time = datetime.datetime.now()
    dates, inputs_converted, inputs_org = [], [], []
    start_date = min_date
    while True:
        end_date = start_date + datetime.timedelta(days=days_len)
        if end_date > max_date:
            break

        start_str, end_str = start_date.strftime('%Y-%m-%d'), end_date.strftime('%Y-%m-%d')
        input_parts = train.loc[train['store'] == store].loc[train['date'] >= start_str].loc[train['date'] < end_str].sort_values(by=['date', 'item'])
        output_parts = train.loc[train['store'] == store].loc[train['date'] == end_str]
        input_ = f'{store}:{start_str[5:]}'
        for item in input_parts['item'].drop_duplicates():
            inputC = f'date{start_str[5:]}:store{store}:item{item}-' + ''.join(input_parts.loc[input_parts['item'] == item, 'sales_processed'].values)
            inputO = f'date{start_str[5:]}:store{store}:item{item}-' + '>'.join(input_parts.loc[input_parts['item'] == item, 'sales'].values)
            dates.append(start_str)
            inputs_converted.append(inputC)
            inputs_org.append(inputO)
        start_date = start_date + datetime.timedelta(days=1)
    records = pd.DataFrame({'date': dates, 'seq_org': inputs_org, 'seq_cnv': inputs_converted})
    records.to_csv(f'data/store{store}_{days_len}days_converted.csv', index=False)
    print(f'dur: {datetime.datetime.now() - start_time}')

In [ ]:
n_store, std_date = 10, '2016-01-01'
train, test = [], []
for i in range(n_store):
    whole = pd.read_csv(f'data/store{i + 1}_{days_len}days_converted.csv')
    train.append(whole.loc[whole['date'] < std_date])
    test.append(whole.loc[whole['date'] >= std_date])
train = pd.concat(train).reset_index(drop=True)
test = pd.concat(test).reset_index(drop=True)
val_idx = np.random.choice(np.arange(len(train)), round(len(train) * 0.1), replace=False)
train_idx = set(np.arange(len(train))) - set(val_idx)
val = train.iloc[sorted(val_idx)]
train = train.iloc[sorted(train_idx)]
train.to_csv(f'train_bert_data/train_{days_len}days.csv', index=False)
val.to_csv(f'train_bert_data/val_{days_len}days.csv', index=False)
test.to_csv(f'train_bert_data/test_{days_len}days.csv', index=False)

In [ ]:
import os
from transformers import BertForMaskedLM, AutoTokenizer, pipeline
from skt.vault_utils import get_secrets

proxy = get_secrets("proxy")["proxy"]
os.environ['HTTP_PROXY'] = proxy
os.environ['HTTPS_PROXY'] = proxy

bert = BertForMaskedLM.from_pretrained('distilbert-base-uncased').cuda()
tokenizer = AutoTokenizer.from_pretrained('distilbert-base-uncased')
fill_mask = pipeline(
    "fill-mask",
    model=bert,
    tokenizer=tokenizer
)

In [ ]:
bert.device

In [ ]:
bert.cpu()
bert.device

In [ ]:
bert.device

In [ ]:
import torch
inputs = tokenizer("Hello, my [MASK] is cute", return_tensors="pt")
print(inputs.input_ids)
with torch.no_grad(): 
    outputs = bert(**inputs)
outputs.prediction_logits

In [ ]:
text = torch("The body was recovered and sent to Cox's Bazar [MASK] morgue for autopsy")
text.cuda()
#fill_mask("The body was recovered and sent to Cox's Bazar [MASK] morgue for autopsy")

In [ ]:
fill_mask("Hello, my [MASK] is cute")[0]['sequence'][6:-6]

In [ ]:
val.head()

In [ ]:
input_ids = tokenizer(list(val['seq_org'])).input_ids

In [ ]:
len(input_ids[0])

In [11]:
import os
from skt.vault_utils import get_secrets
from transformers import RobertaTokenizer, RobertaModel

proxy = get_secrets("proxy")["proxy"]
os.environ['HTTP_PROXY'] = proxy
os.environ['HTTPS_PROXY'] = proxy



In [12]:
from transformers import ElectraTokenizer, ElectraModel, AutoModelForMaskedLM

model = ElectraModel.from_pretrained("monologg/koelectra-base-v3-generator")
lmmodel = AutoModelForMaskedLM.from_pretrained("monologg/koelectra-base-v3-generator")
tokenizer = ElectraTokenizer.from_pretrained("monologg/koelectra-base-v3-generator")

In [17]:
import torch

input_ids = tokenizer("나는 식당에서 밥을 먹었다.").input_ids
md_result = model(torch.tensor([input_ids]))
lmmd_result = lmmodel(torch.tensor([input_ids]))

In [22]:
md_result.last_hidden_state.shape

torch.Size([1, 13, 256])

In [33]:
md_result.last_hidden_state

tensor([[[ 0.0886, -0.1974, -0.0859,  ...,  0.2817,  0.2463, -0.1742],
         [-0.2716, -0.8261,  0.3865,  ...,  0.3734,  0.3926, -0.0354],
         [-0.1466, -0.2909,  0.4556,  ..., -0.0473, -0.0970,  0.0106],
         ...,
         [ 0.7419, -0.2018,  0.0279,  ...,  0.1788, -0.0729, -0.1511],
         [-0.2403,  0.1839, -0.0043,  ..., -0.1352,  0.0159,  0.0375],
         [ 0.0886, -0.1975, -0.0859,  ...,  0.2817,  0.2464, -0.1742]]],
       grad_fn=<NativeLayerNormBackward0>)

In [29]:
lmmd_result = lmmodel.electra(torch.tensor([input_ids]))

In [32]:
lmmd_result.last_hidden_state

tensor([[[ 0.0886, -0.1974, -0.0859,  ...,  0.2817,  0.2463, -0.1742],
         [-0.2716, -0.8261,  0.3865,  ...,  0.3734,  0.3926, -0.0354],
         [-0.1466, -0.2909,  0.4556,  ..., -0.0473, -0.0970,  0.0106],
         ...,
         [ 0.7419, -0.2018,  0.0279,  ...,  0.1788, -0.0729, -0.1511],
         [-0.2403,  0.1839, -0.0043,  ..., -0.1352,  0.0159,  0.0375],
         [ 0.0886, -0.1975, -0.0859,  ...,  0.2817,  0.2464, -0.1742]]],
       grad_fn=<NativeLayerNormBackward0>)

In [10]:
from transformers import pipeline

fill_mask = pipeline(
    "fill-mask",
    model="monologg/koelectra-base-v3-generator",
    tokenizer="monologg/koelectra-base-v3-generator"
)

fill_mask("나는 {} 밥을 먹었다.".format(fill_mask.tokenizer.mask_token))

[{'sequence': '[CLS] 나는 방금 밥을 먹었다. [SEP]',
  'score': 0.09365378320217133,
  'token': 13195,
  'token_str': '방금'},
 {'sequence': '[CLS] 나는 이렇게 밥을 먹었다. [SEP]',
  'score': 0.043304841965436935,
  'token': 15286,
  'token_str': '이렇게'},
 {'sequence': '[CLS] 나는 어제 밥을 먹었다. [SEP]',
  'score': 0.042306043207645416,
  'token': 8108,
  'token_str': '어제'},
 {'sequence': '[CLS] 나는 오늘 밥을 먹었다. [SEP]',
  'score': 0.03583071753382683,
  'token': 6451,
  'token_str': '오늘'},
 {'sequence': '[CLS] 나는 그날 밥을 먹었다. [SEP]',
  'score': 0.029736625030636787,
  'token': 8961,
  'token_str': '그날'}]

In [ ]:
from transformers import pipeline
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = RobertaModel.from_pretrained('roberta-base')
fill_mask = pipeline(
    "fill-mask",
    model='roberta-base'
)

In [ ]:
fill_mask("The man worked as a <mask>.")

In [51]:
import torch.nn as nn

embedding = nn.Embedding(7, 3)
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 5]])
a = embedding(input)

In [50]:
a.shape

torch.Size([2, 4, 3])

In [41]:
a[0]

tensor([[-0.1408, -0.3446,  1.1434],
        [-0.4501, -0.4836, -0.2267],
        [ 0.4594, -0.5137, -0.1693],
        [-1.5105,  0.4170, -0.4267]], grad_fn=<SelectBackward0>)